- name: jenkins container
  docker_container:
    name: jenkins
    image: library/jenkins
    state: present
    exposed_ports:
      - 8080
      - 50000
    volumes:
      - jenkins_home:/var/jenkins_home
  tags: [docker-jenkins]